### ISSUE TITLE
tag and publish releases on github

### ISSUE THREAD

**Issue by saibotk** [khimaros/smart-auto-move#13]
Hey, thank you for your amazing extension.

I'd like to propose to tag releases and publish them here on GitHub, so users can easily get notified and see what is the latest version.

Thanks :)

**Comment by khimaros** [comment]
i'm happy to do this. could you share a bit more about why publishing to the extension store doesn't work for you? are you trying to avoid that service or not comfortable with automatic updates?

**Comment by saibotk** [comment]
No, haha there is no problem with the store at all.

Would just be nice to get the commit tagged that is released to the store for reproducing and testing bugs. 
And an additional publishing here, is just for visibility.
Mainly i'd just like to subscribe to release notes here and follow the development :)

**Comment by khimaros** [comment]
thank you for the request. i've added the first release for v8 and will do for the future as well.
