### ISSUE TITLE
add support for GNOME shell version 40

### ISSUE THREAD

**Issue by wollanup** [khimaros/smart-auto-move#18]
Maybe your extension relies on Gnome 41 exclusive features, but if not, could you consider publishing a Gnome 40 compatible version on [Extensions store](https://extensions.gnome.org/extension/16/auto-move-windows/) ?
Thanks for this project, can't wait to try before Ubuntu 22.04

**Comment by khimaros** [comment]
see instructions for manually installing the extension on unsupported gnome-shell versions here: https://github.com/khimaros/smart-auto-move/issues/24#issuecomment-1298891369
