### ISSUE TITLE
Add ability to exclude apps.

### ISSUE THREAD

**Issue by GDXbsv** [khimaros/smart-auto-move#2]
For example, i am using extension https://extensions.gnome.org/extension/3780/ddterm/.

And smart-auto-move  always move it to the first workspace, but I need it in the current.

This is super extension, but black list would make it superior.

**Comment by terencode** [comment]
Maybe also the ability to exclude all apps and choose which ones to allow (allowlist <-> denylist).

**Comment by khimaros** [comment]
thank you for the request, this is near the top of my priority list.

**Comment by khimaros** [comment]
low level support for this has been implemented in https://github.com/khimaros/smart-auto-move/commit/f57cc5ff0cf3257436d8689a0b52636cdebf9e77 and has been uploaded to extension store for review.

it should be included in version 6 of the extension. there is currently no GUI for changing these settings, so please take a look at https://github.com/khimaros/smart-auto-move/blob/master/README.md#settings

**Comment by khimaros** [comment]
version 6 has now been published to https://extensions.gnome.org/extension/4736/smart-auto-move/

please try it out using the manual dconf settings and let me know if the documentation is clear and fulfills your needs.

**Comment by khimaros** [comment]
filed https://github.com/khimaros/smart-auto-move/issues/4 to track the preferences GUI for this

**Comment by GDXbsv** [comment]
It works 
Thank you for your job
