### ISSUE TITLE
add support for ubuntu 20.04.4 LTS (Gnome 3.36.8)

### ISSUE THREAD

**Issue by justbest23** [khimaros/smart-auto-move#24]
Heyo.

I'm running Ubuntu 20.04 with a few other extensions.

When I try to access the settings on the extention I get "Something's gone wrong" and the following error:

```
Gtk.BuilderError: /home/troggoman/.local/share/gnome-shell/extensions/smart-auto-move@khimaros.com/ui/prefs-gtk4.ui:24:33 Invalid property: GtkNotebook.focusable

Stack trace:
  buildPrefsWidget@/home/troggoman/.local/share/gnome-shell/extensions/smart-auto-move@khimaros.com/prefs.js:41:13
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by khimaros** [comment]
thank you for the report. which version of Gnome She'll are you running? which distro?

**Comment by justbest23** [comment]
Currently using 3.36.8, Ubuntu 20.04 LTS

**Comment by khimaros** [comment]
currently, the only version tested is 41.x

did you manually install the extension from zip?

**Comment by justbest23** [comment]
Ah I see. I installed it from `extensions.gnome.org`

**Comment by SonGokussj4** [comment]
Hi, my company just reinstalled my KDE Centos 7 --> GNOME Rocky Linux 8 (3.36.1 or 3.32.2 - I'm not sure?), and the lack of saving window position totally hurts my brain.

Is it possible to install it somehow?
I've been told I can't install it because it's only for **version 41** on the gnome-extensions website.

```
$ gnome-shell --version
GNOME Shell 3.32.2

$ gjs --version
gjs 1.56.2

$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Rocky
Description:	Rocky Linux release 8.5 (Green Obsidian)
Release:	8.5
Codename:	GreenObsidian
```

**Comment by AJCxZ0** [comment]
Just installed on Ubuntu 20.04 with GNOME 3.36.8 on Wayland with amdgpu, also with a few other extensions. I get same result, plus additional configuration windows showing the error opened while [_Extensions_](https://flathub.org/apps/details/org.gnome.Extensions) is running are unable to be moved or closed until _Extensions_ is closed.
While the Downloads on the [extension page](https://extensions.gnome.org/extension/4736/smart-auto-move/) shows only GNOME 41 and 42, the extension installs and appears to run fine, albeit with configuration via _dconf_.

**Comment by khimaros** [comment]
you can manually install this extension on older version of gnome-shell, but i make no guarantees about behavior.

in fact, the extension may require at least Gtk4 in the more recent versions.

the steps to install the extension manually are:

```
$ git clone https://github.com/khimaros/smart-auto-move
$ make install
```

you will need to log out and back in before enabling the extension.
