### ISSUE TITLE
Smart-Auto-Move Causes Firefox to CRASH

### ISSUE THREAD

**Issue by jtome7** [khimaros/smart-auto-move#27]
Oracle Linux 8.5   with kernel   5.4.17-2136.305.5.4.el8uek.x86_64

Gnome Shell Extension smart-auto-move causes Firefox to crash:

Apr  7 10:53:54 falcon journal[31858]: [smart-auto-move] handleChangedDebugLogging(): false
Apr  7 10:53:55 falcon journal[31858]: [smart-auto-move] handleChangedDebugLogging():
false
Apr  7 10:53:56 falcon journal[31858]: [smart-auto-move] handleChangedDebugLogging(): false
Apr  7 10:53:57 falcon journal[31858]: [smart-auto-move] handleChangedDebugLogging(): false
Apr  7 10:53:58 falcon journal[31858]: [smart-auto-move] handleChangedDebugLogging(): false

         ~~~~~~~~~~~~~~~~~~~~

Gtk.BuilderError: /home/jtome/.local/share/gnome-shell/extensions/smart-auto-move@khimaros.com/ui/prefs-gtk4.ui:24:33 Invalid property: GtkNotebook.focusable

Stack trace:
  buildPrefsWidget@/home/jtome/.local/share/gnome-shell/extensions/smart-auto-move@khimaros.com/prefs.js:41:5
  _showPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:55:22
  _extensionsLoaded@resource:///org/gnome/shell/extensionPrefs/main.js:308:13
  _scanExtensions/<@resource:///org/gnome/shell/extensionPrefs/main.js:286:13
  asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:131:13
  main@resource:///org/gnome/shell/extensionPrefs/main.js:691:5
  @<main>:1:43

**Comment by khimaros** [comment]
@jtome7 have you confirmed that it is crashing and not simply being moved to a different workspace?

**Comment by khimaros** [comment]
it would help to have the console output of firefox when this happens.

**Comment by jtome7** [comment]
I had Firefox browser windows running in four (4) Linux workspaces and they
all disappeared in one fell swoop.  It scared me the first time it happened
because I thought there was a power outage and the server was fried.  But
then, I realized that everything was still up & running except the Firefox
browser windows.  So they all disappeared.  They were not moved to a
different workspace.  They were simply gone.

Your idea for this extension is fantastic!  Keep up the great work.

If I can get any further information, I'll forward it to you.


*Thanks!**Joel*


*************************** Joel Tome *

*jtome7 @ gmail.com <http://gmail.com>****************************

**Comment by khimaros** [comment]
do you have any specific reason to believe the crash is caused by smart-auto-move?

i'm not aware of any mechanism by which it's possible for a gnome-shell extension to crash another program.

**Comment by khimaros** [comment]
@jtome7 i haven't heard from you in a while. please let me know if this is still impacting you, otherwise i will be closing the issue due to inability to reproduce.
