### ISSUE TITLE
restore always-on-top and always-visible state

### ISSUE THREAD

**Issue by 0chroma** [khimaros/smart-auto-move#30]
hi, I've been using this extension recently and it's been really helpful! I use Always on Top + Always on Visible Workspace fairly often since I want to keep calls and videos open when switching between workspaces, it would be great if smart auto move supported that!

**Comment by creinig** [comment]
This is also *very* useful for e.g. thunderbird reminder windows etc

**Comment by khimaros** [comment]
i've released https://github.com/khimaros/smart-auto-move/releases/tag/v19 which contains commit https://github.com/khimaros/smart-auto-move/commit/dea6f57389a4dba30f5200af91134ce43ada28d9 -- this adds support for "above" and "on-all-workspaces" properties, which i believe should solve both of the requests in this issue.

**Comment by ankostis** [comment]
In Wayland i tried to toggle  eg. a terminal window as "Always visible" both from its Window menu and with the shortcut  _"Gnome Settings | Keyboard | Windows | Toggle Window on all workspaces or one"_ ,
i closed it and reopened it, and it was not toggled (it was visible only on the Workspace i was on).

Is this expected?

- Debian unstable (SID)
-  Gnome shell: 44.7
-  smart-auto-move-20
