### ISSUE TITLE
How to Set "IGNORE" for All Thunderbird Compose Windows

### ISSUE THREAD

**Issue by moore-bryan** [khimaros/smart-auto-move#33]
There doesn't seem to be a way, or I am _completely_ missing it, to set Smart Auto Move to _always_ ignore the Thunderbird compose window and allow it to remain at the default location; that is, for some reason the compose window snaps to the right side of my screen, becomes unmovable unless I maximize it, and turning off the extension completely allows it to behave normally. In "Overrides," there's no way to add anything like "Thunderbird Write" and there is a different listing for _each_ compose window I've ever used in the "Saved Windows" tab.

I appreciate any help.

Fedora 36 with GNOME Shell 42.5, Wayland, and Kernel 5.19.16-200.fc36.x86_64.

**Comment by zanovis** [comment]
Are you using Static Workspaces? Settings > Multitasking > Workspaces > Static Workspaces

Reference: https://github.com/khimaros/smart-auto-move/issues/22

**Comment by moore-bryan** [comment]
Thanks for the suggestion and the link... Just changed it from "Dynamic workspace" to "Fixed number of workspaces," rebooted, and the behavior remains.

**Comment by khimaros** [comment]
@moore-bryan the solution should be to visit the `Saved Windows` tab and click `OVERRIDE (ANY)` on the thunderbird window. then visit the `Overrides` tab and change the behavior to `IGNORE`.

there is currently no other way to choose a window or application eg. by searching through a list of applications or selecting the window by point-and-click. it's on the roadmap though!

**Comment by khimaros** [comment]
see also https://github.com/khimaros/smart-auto-move/issues/34
