### ISSUE TITLE
follow window if it is moved to another workspace

### ISSUE THREAD

**Issue by rockerbacon** [khimaros/smart-auto-move#36]
I found this old issue https://github.com/khimaros/smart-auto-move/issues/20, which was closed as completed but there doesn't seem to be any such option and I couldn't find any code for workspace activation in the current codebase.

I imagine this feature would have the same usability issues I discovered while looking into such feature for auto-move-windows. I have already proposed the solution I'm currently using in their issue tracker (which you can read on the last comment in the [original issue](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/issues/1)).
I still haven't heard back from the auto-move-windows devs and I'd really rather work on an existing extension rather than creating my own. If the feature interests you in any capacity I'd gladly put in the work to have the feature in smart-auto-move.

**Comment by khimaros** [comment]
@rockerbacon i'd be happy to accept a pull request to add this feature!

**Comment by khimaros** [comment]
i've released https://github.com/khimaros/smart-auto-move/releases/tag/v19 which contains commit https://github.com/khimaros/smart-auto-move/commit/dea6f57389a4dba30f5200af91134ce43ada28d9 -- there is a new preference option "Activate Workspace" which is enabled by default. when enabled, any time a window is moved by smart-auto-move to another workspace, that workspace will be activate. i believe this is now done.
