### ISSUE TITLE
Gnome 44 support?

### ISSUE THREAD

**Issue by ionutbortis** [khimaros/smart-auto-move#39]
First of all, thank you for this awesome extension! :pray: 

Are there any plans to support the latest Gnome version, 44?
Both Fedora 38 and Ubuntu 23.04 are already out and shipped with Gnome 44 :grimacing: 

Gnome Extensions are usually the main factor for postponing distro upgrades :sweat_smile:

**Comment by khimaros** [comment]
thank you for your contribution @ionutbortis -- merged https://github.com/khimaros/smart-auto-move/pull/40
