### ISSUE TITLE
implement basic extension preferences GUI

### ISSUE THREAD

**Issue by khimaros** [khimaros/smart-auto-move#4]
key preferences to support:

- [x] simple toggle for debug logging
- [x] ability to "forget" a saved window
- [x] switch sync mode between IGNORE and RESTORE

**Comment by terencode** [comment]
Another idea : choose which information should be saved for either all windows or per app/window.
For example, I want to be able to choose not to remember on which workspace a window was last opened.
Also, when a window is restored on a different workspace, maybe add an option to switch to this workspace.

**Comment by khimaros** [comment]
> Another idea : choose which information should be saved for either all windows or per app/window.

i've opened a new issue to track this at #7

**Comment by khimaros** [comment]
this is now available in version 8 on the extension store
