### ISSUE TITLE
Gnome 45 support?

### ISSUE THREAD

**Issue by ionutbortis** [khimaros/smart-auto-move#44]
Hi and thank you for this awesome extension!

Honestly, I don't think I could go back to gnome not remembering window sizes and positions :sweat_smile: 

Are there any plans in supporting the next Gnome Shell version, 45?
I'm asking this because the gnome shell devs kinda broke all the extensions with this new release...

There is no backwards compatibility with previous versions and not all the previously exposed objects are available anymore, due to the ecma script modules transition :worried: => https://gjs.guide/extensions/upgrading/gnome-shell-45.html

My extension doesn't have a large codebase so I was able to properly adapt it for 45 in a timely manner.

**Comment by ionutbortis** [comment]
@khimaros 
I created #45 PR for the Gnome 45 support. Let me know what you think!

Thanks,
Ionut

**Comment by ionutbortis** [comment]
I also attached here the build for the gnome 45 port. For testing and maybe for submission to EGO if you want to skip a Gnome 45 vm install. Thanks!

[smart-auto-move@khimaros.com.shell-extension.zip](https://github.com/khimaros/smart-auto-move/files/13418637/smart-auto-move%40khimaros.com.shell-extension.zip)

**Comment by Tyrbiter** [comment]
I have substituted the files from this zip file instead of the originals, so far it appears to work well.

A very welcome offering, it's such a useful extension.

**Comment by Bytezz** [comment]
Since I'm still on Gnome 44, I tried it on Gnome OS Nightly inside Gnome Boxes and it works.

[SAM on Gnome OS Nightly](https://github.com/khimaros/smart-auto-move/assets/25850701/61c9a600-9806-42f1-bbd5-808738df18e2)

**Comment by ionutbortis** [comment]
@Bytezz @Tyrbiter Nice, thanks for testing it out!

I'm not sure if it's a bug or a feature, but I love this way of handling terminals via SAM. First one opens snapped to half right, the next ones snapped to half left :star_struck: 

[Screencast from 2023-11-22 18-23-26.webm](https://github.com/khimaros/smart-auto-move/assets/5013697/9c988988-0f1b-41bc-9395-153a88036eaa)

**Comment by KataFF** [comment]
Smart Auto Move works on up-to-date Manjaro/Arch no problem on GNOME 45.3., and has worked at least since 45.1 and three months back. Perhaps the issue can be closed, especially if other popular distros get tested working (Debian Bookworm, Ubuntu, Fedora etc.)?

**Comment by ionutbortis** [comment]
> Smart Auto Move works on up-to-date Manjaro/Arch no problem on GNOME 45.3., Wayland session, and has worked at least since 45.1 and three months back. Perhaps the issue can be closed, especially if other popular distros get tested working (Debian Bookworm, Ubuntu, Fedora etc.)?

That's weird. There isn't any official release for Gnome 45. Maybe someone bundled the modified version to an AUR package.

@khimaros previously said that he's on Debian testing and that distro is still on 44.8. I was given the impression that he will properly update the extension to 45 when Debian testing will also get to gnome shell 45.

**Comment by khimaros** [comment]
i have just tested this with GnomeOS nightly and can confirm that basic functionality is there. i'm going to look at the linked PR shortly and merge.

thank you @ionutbortis for your work on this and for your (extreme) patience.

**Comment by khimaros** [comment]
fixed by #45 -- thank you again @ionutbortis

**Comment by khimaros** [comment]
reopening until this is available on EGO.

**Comment by SebTM** [comment]
Hey, sorry for my missing context but what is EGO? Could you also draft a release so I can update the extension for NixOS? (https://search.nixos.org/packages?query=smart-auto-move&channel=unstable)

**Comment by teatwig** [comment]
EGO = extensions.gnome.org

**Comment by khimaros** [comment]
@SebTM coincidentally, i'm looking at using a NixOS virtual machine to automate testing on multiple versions of GNOME. do you have a configuration.nix which could run multiple versions of GNOME in the same NixOS install? i will manually push the smart-auto-move extension to the VM from the host so i won't be using your extension package.

**Comment by khimaros** [comment]
this is the version which should be making it's way to EGO (pending approval)

[smart-auto-move@khimaros.com.shell-extension.zip](https://github.com/khimaros/smart-auto-move/files/15059440/smart-auto-move%40khimaros.com.shell-extension.zip)

**Comment by SebTM** [comment]
> i'm looking at using a NixOS virtual machine to automate testing on multiple versions of GNOME. do you have a configuration.nix which could run multiple versions of GNOME in the same NixOS install?

Hey, sorry for the delay - I think it's possible but due to NixOS / Nixpkgs not maintaining multiple gnome-versions in a package-set you would need to construct a flake with different nixpkgs-inputs and build vms of them with the corresponding versions I would say. Maybe join the NixOS Gnome channel on matrix and ask for support there - I'm sure people are willing to help setup a nix-based environment to automate/simplify maintenance as this could be adopted by other extensions later :)

**Comment by SebTM** [comment]
> published to extensions.gnome.org and tagged as release v25

Share the info in the channel mentioned above maybe it can be included in the gnome-46 merge still 🙏🏻

**Comment by SebTM** [comment]
FYI: NixOS - v26 included in https://github.com/NixOS/nixpkgs/pull/306197
