### ISSUE TITLE
Gnome 46 support?

### ISSUE THREAD

**Issue by a1ex-ak** [khimaros/smart-auto-move#47]
Kindly tell me when support for Gnome 46 is possible. I really like your extension.

**Comment by diabeetus01** [comment]
Same here, I've been curious about writing extensions so gonna poke around the source of this one and see if anything can get it working for 46, similar to the other person who got it working in 45 prior.

**Comment by a1ex-ak** [comment]
> Same here, I've been curious about writing extensions so gonna poke around the source of this one and see if anything can get it working for 46, similar to the other person who got it working in 45 prior.

I will be very grateful))
Thank you

**Comment by khimaros** [comment]
it's possible that there are no additional code changes needed beyond what was done for 45. you could try manually installing the zip from https://github.com/khimaros/smart-auto-move/issues/44#issuecomment-1819661126

note: i have not verified this package.

**Comment by a1ex-ak** [comment]
> it's possible that there are no additional code changes needed beyond what was done for 45. you could try manually installing the zip from [#44 (comment)](https://github.com/khimaros/smart-auto-move/issues/44#issuecomment-1819661126)
> 
> note: i have not verified this package.

It works, but not for all applications.
In particular, Telegram does not always work as expected

**Comment by khimaros** [comment]
do you know if telegram is built for x11 or wayland?

**Comment by a1ex-ak** [comment]
> do you know if telegram is built for x11 or wayland?

wayland

**Comment by khimaros** [comment]
it will be possible to install on GNOME 46 after the release of v21, just pending review from the EGO team.

**Comment by khimaros** [comment]
published to extensions.gnome.org and tagged as release v25

https://github.com/khimaros/smart-auto-move/releases/tag/v25
